version: '3.3'
services:
    rancher:
        privileged: true
        restart: always
        container_name: rancher
        command: --no-cacerts
        ports:
            - '80:80'
            - '443:443'

        image: rancher/rancher:latest

        environment:
          - CATTLE_BOOTSTRAP_PASSWORD=${CATTLE_BOOTSTRAP_PASSWORD}
          
        # Specify your domain name
        hostname: devrancher.asliri.id

        volumes:
          - ./data:/var/lib/rancher
          - ./certs:/etc/rancher/ssl
          - ./certs/asliri-id-23-24.crt:/etc/rancher/ssl/cert.pem
          - ./certs/asliri-id-23-24.key:/etc/rancher/ssl/key.pem