pipeline {
    agent any
    environment {
        RANCHER_URL = 'https://devrancher.asliri.id/'  // Replace with your Rancher URL
        RANCHER_ACCESS_KEY = 'token-fsgwq'
        RANCHER_SECRET_KEY = '8m5jp8x56lp4kl8hhjp4ckfgzngfdrvbc79l7clfr6th69tgbkwprb'
        CLUSTER_ID = 'aslirid-cluster-dev'  // Replace with your cluster ID
        NODE_TEMPLATE_ID = 'rancher-ubuntu-template'  // Replace with your node template ID
    }
    stages {
        stage('Create Worker Node') {
            steps {
                script {
                    sh """
                        rancher login $RANCHER_URL --token $RANCHER_ACCESS_KEY:$RANCHER_SECRET_KEY
                        rancher clusters get $CLUSTER_ID > cluster.yml
                        rancher nodes add -c cluster.yml --template $NODE_TEMPLATE_ID
                    """
                }
            }
        }
    }
    post {
        success {
            echo 'Add worker node on asliri-cluster successfully'
        }
        failure {
            echo 'Add worker node on asliri-cluster failed'
        }
    }
}
