pipeline {
    agent any
    environment {
        RANCHER_URL = 'https://rancher.server/'  // Replace with your Rancher URL
        RANCHER_ACCESS_KEY = 'token-xmf6q'
        RANCHER_SECRET_KEY = '7btxpnfgxg6dd6z7m59nsf5p8nz7lz79lmf745cgf7r8ksmt5p6ssr'
        CLUSTER_ID = 'aslirid-cluster'  // Replace with your cluster ID
        NODE_TEMPLATE_ID = 'default-node-template-ubuntu'  // Replace with your node template ID
    }
    stages {
        stage('Create Worker Node') {
            steps {
                script {
                    sh """
                        rancher login $RANCHER_URL --token $RANCHER_ACCESS_KEY:$RANCHER_SECRET_KEY
                        rancher clusters get $CLUSTER_ID > cluster.yml
                        rancher nodes add -c cluster.yml --template $NODE_TEMPLATE_ID
                    """
                }
            }
        }
    }
    post {
        success {
            echo 'Add worker node on asliri-cluster successfully'
        }
        failure {
            echo 'Add worker node on asliri-cluster failed'
        }
    }
}
