pipeline {
    agent any
    
    stages {
        stage('Add Worker Node to Rancher Cluster') {
            steps {
                script {
                    def rancherUrl = 'https://rancher.server/v3/clusters' // Replace with your Rancher URL
                    def apiKey = 'token-sxpzx'
                    def apiSecret = 'p48sv8lxkxx2rkgvq7bg7brvslgk68fgz28sjfhgm7plnc5ms6xmdc'
                    def clusterID = 'aslirid-cluster' // Replace with your Rancher cluster ID
                    def nodeTemplateName = 'default-node-template-ubuntu' // Replace with your node template name
                    def nodeConfig = """
                        {
                            "hostnamePrefix": "	aslirid-worker",
                            "worker": true,
                            "etcd": true,
                            "controlPlane": true,
                            "clusterId": "${clusterID}",
                            "nodeTemplateName": "${nodeTemplateName}"
                        }
                    """
                    
                    def response = httpRequest(
                        url: "${rancherUrl}/${clusterID}/nodes",
                        authentication: 'rancher-credential',
                        usernamePasswordVariable: "${apiKey}",
                        httpMode: 'POST',
                        requestBody: 'nodeConfig'
                    )

                    if (response.status == 201) {
                        echo "Worker node addition request successful."
                    } else {
                        error "Worker node addition request failed. HTTP status code: ${response.status}"
                    }
                }
            }
        }
    }
}
