# kibana-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-deployment
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: kibana:7.17.1
          volumeMounts:
            - name: kibana-config
              mountPath: /usr/share/kibana/config/kibana.yml
              subPath: kibana.yml
          ports:
            - containerPort: 5601
          env:
            - name: ELASTICSEARCH_URL
              value: https://dev-elastic.asliri.id/ # Replace with your Elasticsearch service name
      volumes:
          - name: kibana-config
            configMap:
              name: kibana-config

---
# kibana-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: kibana-service
  namespace: monitoring
spec:
  #type: NodePort
  selector:
    app: kibana
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
  
