apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: infra
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      nodePort: 30090
  
