apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana-cluster-role
  namespace: monitoring
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-cluster-role-binding
  namespace: monitoring
subjects:
  - kind: ServiceAccount
    name: grafana-service-account
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: grafana-cluster-role
  apiGroup: rbac.authorization.k8s.io
